In [1]:
import cirq
from qiskit import *

In [2]:
qc = cirq.Circuit()
qubits = cirq.GridQubit.rect(1,4)
qc.append(cirq.CNOT(qubits[0], qubits[3]))
qc.append(cirq.CNOT(qubits[0], qubits[2]))

In [3]:
qc

(0, 0): ───@───@───
           │   │
(0, 2): ───┼───X───
           │
(0, 3): ───X───────

In [7]:
type(QuantumCircuit.from_qasm_str(qc.to_qasm()).draw('mpl'))

matplotlib.figure.Figure

In [3]:
a = (3,3)
isinstance(a,int)

False

In [5]:
import numpy as np

In [13]:
i = np.array((4,4))
k = np.array((3,3))
np.ceil(i/k)

array([2., 2.])

In [14]:
import tensorflow as tf

2022-07-05 20:57:56.486832: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-07-05 20:57:56.486869: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [15]:
a = tf.constant([[1,2,3],[4,5,6]], tf.int32)

2022-07-05 20:58:21.429041: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-07-05 20:58:21.429086: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (bhagvada): /proc/driver/nvidia/version does not exist
2022-07-05 20:58:21.432303: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [19]:
a == tf.tile(a,[1,1])

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True]])>